spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/dahongbao
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379

mybatis:
  mapper-locations: mapper/*Mapper.xml